// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/types/Address.proto

package address

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_NEW     Status = 0
	Status_UPDATED Status = 1
	Status_DELETED Status = 2
)

var Status_name = map[int32]string{
	0: "NEW",
	1: "UPDATED",
	2: "DELETED",
}

var Status_value = map[string]int32{
	"NEW":     0,
	"UPDATED": 1,
	"DELETED": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e8cf9af71f2125bf, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8cf9af71f2125bf, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type AddressObject struct {
	Address              string            `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	DataType             string            `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType,omitempty"`
	Options              map[string][]byte `protobuf:"bytes,3,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Readable             bool              `protobuf:"varint,4,opt,name=Readable,proto3" json:"Readable,omitempty"`
	Writable             bool              `protobuf:"varint,5,opt,name=Writable,proto3" json:"Writable,omitempty"`
	Status               Status            `protobuf:"varint,6,opt,name=status,proto3,enum=adsrv.address.Status" json:"status,omitempty"`
	Value                []byte            `protobuf:"bytes,7,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddressObject) Reset()         { *m = AddressObject{} }
func (m *AddressObject) String() string { return proto.CompactTextString(m) }
func (*AddressObject) ProtoMessage()    {}
func (*AddressObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8cf9af71f2125bf, []int{1}
}

func (m *AddressObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressObject.Unmarshal(m, b)
}
func (m *AddressObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressObject.Marshal(b, m, deterministic)
}
func (m *AddressObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressObject.Merge(m, src)
}
func (m *AddressObject) XXX_Size() int {
	return xxx_messageInfo_AddressObject.Size(m)
}
func (m *AddressObject) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressObject.DiscardUnknown(m)
}

var xxx_messageInfo_AddressObject proto.InternalMessageInfo

func (m *AddressObject) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddressObject) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *AddressObject) GetOptions() map[string][]byte {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *AddressObject) GetReadable() bool {
	if m != nil {
		return m.Readable
	}
	return false
}

func (m *AddressObject) GetWritable() bool {
	if m != nil {
		return m.Writable
	}
	return false
}

func (m *AddressObject) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_NEW
}

func (m *AddressObject) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type AddressSub struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=Ids,proto3" json:"Ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressSub) Reset()         { *m = AddressSub{} }
func (m *AddressSub) String() string { return proto.CompactTextString(m) }
func (*AddressSub) ProtoMessage()    {}
func (*AddressSub) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8cf9af71f2125bf, []int{2}
}

func (m *AddressSub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressSub.Unmarshal(m, b)
}
func (m *AddressSub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressSub.Marshal(b, m, deterministic)
}
func (m *AddressSub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressSub.Merge(m, src)
}
func (m *AddressSub) XXX_Size() int {
	return xxx_messageInfo_AddressSub.Size(m)
}
func (m *AddressSub) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressSub.DiscardUnknown(m)
}

var xxx_messageInfo_AddressSub proto.InternalMessageInfo

func (m *AddressSub) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Chunk struct {
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8cf9af71f2125bf, []int{3}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Value struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8cf9af71f2125bf, []int{4}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Value) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("adsrv.address.Status", Status_name, Status_value)
	proto.RegisterType((*Empty)(nil), "adsrv.address.Empty")
	proto.RegisterType((*AddressObject)(nil), "adsrv.address.AddressObject")
	proto.RegisterMapType((map[string][]byte)(nil), "adsrv.address.AddressObject.OptionsEntry")
	proto.RegisterType((*AddressSub)(nil), "adsrv.address.AddressSub")
	proto.RegisterType((*Chunk)(nil), "adsrv.address.Chunk")
	proto.RegisterType((*Value)(nil), "adsrv.address.Value")
}

func init() { proto.RegisterFile("api/proto/types/Address.proto", fileDescriptor_e8cf9af71f2125bf) }

var fileDescriptor_e8cf9af71f2125bf = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x5f, 0x8b, 0x9b, 0x40,
	0x14, 0xc5, 0xab, 0x56, 0x4d, 0x6f, 0x92, 0x12, 0x86, 0x16, 0x24, 0x90, 0x22, 0x3e, 0xd9, 0x96,
	0x28, 0xa4, 0x0f, 0x69, 0xd3, 0xa7, 0x34, 0xfa, 0x10, 0x28, 0x4d, 0x31, 0xd9, 0x0d, 0xec, 0xdb,
	0x18, 0x87, 0xc4, 0xcd, 0x1f, 0xc5, 0x19, 0x03, 0x7e, 0xbe, 0xfd, 0x62, 0xcb, 0x8c, 0x93, 0x7f,
	0xcb, 0xb2, 0x4f, 0xfa, 0xbb, 0xe7, 0x1e, 0x8e, 0xf7, 0x20, 0xf4, 0x70, 0x9e, 0xfa, 0x79, 0x91,
	0xb1, 0xcc, 0x67, 0x55, 0x4e, 0xa8, 0x3f, 0x4e, 0x92, 0x82, 0x50, 0xea, 0x89, 0x19, 0x6a, 0xe3,
	0x84, 0x16, 0x47, 0x0f, 0xd7, 0x43, 0xc7, 0x04, 0x3d, 0xdc, 0xe7, 0xac, 0x72, 0x9e, 0x54, 0x68,
	0xcb, 0xcd, 0x59, 0xfc, 0x48, 0x56, 0x0c, 0x59, 0x60, 0xca, 0x81, 0xa5, 0xd8, 0x8a, 0xfb, 0x21,
	0x3a, 0x21, 0xea, 0x42, 0x23, 0xc0, 0x0c, 0x2f, 0xaa, 0x9c, 0x58, 0xaa, 0x90, 0xce, 0x8c, 0x26,
	0x60, 0xce, 0x72, 0x96, 0x66, 0x07, 0x6a, 0x69, 0xb6, 0xe6, 0x36, 0x07, 0x5f, 0xbd, 0x9b, 0x44,
	0xef, 0x26, 0xc4, 0x93, 0xbb, 0xe1, 0x81, 0x15, 0x55, 0x74, 0x72, 0xf2, 0x80, 0x88, 0xe0, 0x04,
	0xc7, 0x3b, 0x62, 0xbd, 0xb7, 0x15, 0xb7, 0x11, 0x9d, 0x99, 0x6b, 0xcb, 0x22, 0x65, 0x42, 0xd3,
	0x6b, 0xed, 0xc4, 0xa8, 0x0f, 0x06, 0x65, 0x98, 0x95, 0xd4, 0x32, 0x6c, 0xc5, 0xfd, 0x38, 0xf8,
	0xfc, 0x22, 0x7b, 0x2e, 0xc4, 0x48, 0x2e, 0xa1, 0x4f, 0xa0, 0xdf, 0xe3, 0x5d, 0x49, 0x2c, 0xd3,
	0x56, 0xdc, 0x56, 0x54, 0x43, 0x77, 0x04, 0xad, 0xeb, 0xaf, 0x42, 0x1d, 0xd0, 0xb6, 0xa4, 0x92,
	0x1d, 0xf0, 0x57, 0xee, 0x3b, 0x0a, 0x9f, 0x5a, 0xfb, 0x04, 0x8c, 0xd4, 0x9f, 0x8a, 0xf3, 0x05,
	0x40, 0xde, 0x37, 0x2f, 0x63, 0xee, 0x9c, 0x26, 0xbc, 0x3d, 0x8d, 0x3b, 0xa7, 0x09, 0x75, 0x7a,
	0xa0, 0x4f, 0x36, 0xe5, 0x61, 0x7b, 0x89, 0x56, 0xaf, 0xa2, 0x9d, 0xa1, 0x9c, 0xbe, 0xd1, 0xfd,
	0xab, 0xc6, 0x6f, 0xdf, 0xc1, 0xa8, 0x6f, 0x43, 0x26, 0x68, 0xff, 0xc2, 0x65, 0xe7, 0x1d, 0x6a,
	0x82, 0x79, 0xf7, 0x3f, 0x18, 0x2f, 0xc2, 0xa0, 0xa3, 0x70, 0x08, 0xc2, 0xbf, 0x21, 0x07, 0xf5,
	0xcf, 0xaf, 0x87, 0xe1, 0x3a, 0x65, 0x9b, 0x32, 0xf6, 0x56, 0xd9, 0xde, 0x2f, 0xb2, 0x84, 0x14,
	0x7b, 0x7f, 0x9d, 0xf5, 0x45, 0x57, 0xfe, 0xe5, 0xf7, 0x59, 0x67, 0xbe, 0x2c, 0xee, 0xb7, 0x7c,
	0xc6, 0x86, 0x50, 0x7e, 0x3c, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x84, 0x8a, 0xe5, 0x65, 0x02,
	0x00, 0x00,
}
